services:
  - type: web
    name: echo-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=$PYTHONPATH:. uvicorn src.backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000

  - type: web
    name: echo-frontend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Echo.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BACKEND_URL
        value: https://echo-backend.onrender.com # You'll need to update this with your actual backend URL